### PR TITLE
fix(infra): Separate clickup-projen into different packageRule

### LINKED ISSUE #128: Action Required: Fix Renovate Configuration
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Location: `renovate.json5`
Error type: The renovate configuration file contains some invalid settings
Message: `packageRules[0]: packageRules cannot combine both matchUpdateTypes and allowedVersions. Rule: {"groupName":"all non-major dependencies","groupSlug":"all-minor-patch","matchPackagePatterns":["*"],"matchUpdateTypes":["minor","patch"],"automerge":true,"addLabels":["auto-approve"],"allowedVersions":"!/^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?-(alpha|beta).*$/"}`

### PR DESCRIPTION
**Pull request by Justinon**
Fixes #128 

https://click-up.slack.com/archives/C05RL91C490/p1694534858319609

### CODE REVIEW

File: src/renovate-workflow.ts [hunk 1]
```diff
@@ -119,20 +119,24 @@ export module renovateWorkflow {
               groupName: 'all non-major dependencies',
               groupSlug: 'all-minor-patch',
               matchPackagePatterns: ['*'],
+              excludePackagePatterns: ['^@time-loop\\/clickup-projen'],
```
Comment (ahammond) [inline src/renovate-workflow.ts:122]: Hmm... I thought we moved this out of Renovate completely? https://github.com/time-loop/clickup-projen/pull/196 maybe missed this part?

**Review by ahammond — APPROVED** [review]
